### ISSUE TITLE
Typage dans les paramètres de requêtes

### ISSUE THREAD

**Issue by ArthurHtbk** [aimach/request-builder#1]
Coucou

Petit point d'amélioration possible dans la gestion des types de données : dans les queries et le body (pas dans les params parce que ça ne s'applique pas), le type est string par défaut et int quand l'input détecte un int (cf photo 1 & 2), mais quand on écrit une chaîne de caractères qui commence par un ou des chiffres, dans l'objet ça va forcément être typé int (cf photo 3). Peut-être pourrais-tu faire une regex qui va détecter la présence de caractères alphabétiques et spéciaux pour typer en string ?

<img width="1642" alt="Capture d’écran 2023-09-04 à 14 44 18" src="https://github.com/aimach/request-builder/assets/78815489/5b270283-e2d3-49e7-963d-3f1fdfea8bff">
<img width="1644" alt="Capture d’écran 2023-09-04 à 14 49 25" src="https://github.com/aimach/request-builder/assets/78815489/6bb5a98d-8285-486e-9355-d10732b79e78">
<img width="1645" alt="Capture d’écran 2023-09-04 à 14 50 44" src="https://github.com/aimach/request-builder/assets/78815489/c5fd1107-990b-4be9-b66d-fe0b72297638">

**Comment by ArthurHtbk** [comment]
J'ai dit une bêtise : le problème est aussi présent avec les params dans l'objet reçu.

**Comment by aimach** [comment]
C'est bon, c'est corrigé avec une regex !
