### ISSUE TITLE
Formatage des params sur la route "/" du serveur

### ISSUE THREAD

**Issue by ArthurHtbk** [aimach/request-builder#2]
Les params que tu mets s'affichent bien dans la route côté et client et côté serveur (cf photo 1), mais si pour une raison ou pour une autre on a besoin de params dans une route dont le endpoint est "/", alors on se retrouve avec des URL mal formatées, avec "//value" côté client et "//:value" côté serveur (cf photo 2).  

<img width="1645" alt="Capture d’écran 2023-09-04 à 16 15 46" src="https://github.com/aimach/request-builder/assets/78815489/e4bce431-289b-4a12-bb65-81ee61eabb5c">
<img width="1651" alt="Capture d’écran 2023-09-04 à 16 17 12" src="https://github.com/aimach/request-builder/assets/78815489/f6d787c8-43fc-4f33-ac1b-1cef846bb753">

**Comment by aimach** [comment]
Résolu !
