### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by ArthurHtbk** [aimach/request-builder#4]
Fautes/maladresses en anglais, liste que j'espère exhaustive, je n'hésiterai pas à aller en commentaires si je remarque des choses à l'avenir : 

- The request you _**sent**_ with fetch, axios or Postman => The request you _**send**_ with fetch, axios or Postman
- req.body you must _**sent**_ => req.body you must _**send**_
- The route _**you must have**_ in your router => The route _**you have**_ in your router
- Tuto, étape "The form" : For every field, you have a help button that displays _**a definition**_ about the query item." => "For every field, you have a help button that displays _**some information**_ about the query item.
- Tuto, étape "Request Information" : "You can add a body (except for the GET method), params, and _**query**_." => "You can add a body (except for the GET method), params, and _**queries**_.", "We have 1 params (type) and 2 _**query**_ (color and limit)." => "We have 1 params (type) and 2 _**queries**_ (color and limit)."
- Tuto, étape "The Result" : On the right, a set of information is displayed that will help you understand what you need to send _**on the client side**_ and what you'll receive _**on the server side**_. => On the right, a set of information is displayed that will help you understand what you need to send _**from the front end**_ and what you'll receive _**on the back end**_.
- Tuto, étape "Client side" (que je renommerais sûrement en "Front End" : "...the address you'll use _**in**_ fetch, axios... => ...the address you'll use _**with**_ fetch, axios...", "...the request's _**adress**_..." => "...the request's _**address**_..."
- Tuto, étape "Server Side" : je la renommerais probablement "Back End". En fait, je serais toi, je renommerais toutes les occurrences de "client side" en "front end" (avec l'espace, sauf si c'est un adjectif (ex : "the _**front end**_ of an application", mais "a _**front-end**_ framework")), et celles de "server side" en "back end" (pareil que pour front end). C'est peut-être juste moi, mais ça me paraît plus clair...
- Bulles d'aide : j'ai tout lu, c'est parfait !

Bon, mis à part ces petits trucs, tout est très bien 🙂

**Comment by aimach** [comment]
Merci beaucoup !!
